Vagrant.configure("2") do |config|
    (1..2).each do |i|
        config.vm.define "cliente#{i}" do |cliente|
            cliente.vm.box = "daimler/ubuntu-23.10.1-desktop"
            config.vm.hostname = "cleinte-#{i}"
            cliente.vm.network "public_network", bridge: "enp63s0", ip: "192.168.0.12#{i}"
            #cliente.vm.provision "shell", path: "auto.sh"
        end
    end
end
#Vagrant.configure("2") do |config|
#    (1..2).each do |i|
#      config.vm.define "web_#{i}" do |web|
#        web.vm.box = "centos/7"
#        web.vm.network :public_network, bridge: "enp63s0", ip: "192.168.0.12#{i}"
#        web.vm.provision "shell", path: "auto.sh"
#      end
#    end
#  end
  