Vagrant.configure("2") do |config|
  (1..2).each do |i|
      config.vm.define "VM#{i}" do |cliente|
          cliente.vm.box = "daimler/ubuntu-23.10.1-desktop"
          config.vm.hostname = "VM#{i}"
          cliente.vm.network "public_network", bridge: "enp63s0", ip: "192.168.0.12#{i}"
          #cliente.vm.provision "shell", path: "auto.sh"
      end
  end
end